refresh_vehicle_data:
  name: Refresh vehicle data
  description: > Request an update of the state from the vehicle, 
  as opposed to the normal update mechanism, which only retrieves data from the servers.
  fields:
    vin:
      name: VIN
      description: your vehicle
      required: true
      selector:
        device:
          integration: audiconnect

execute_vehicle_action:
  name: Execute vehicle action
  description: > Request an update of the state from the vehicle, as opposed to the normal 
  update mechanism, which only retrieves data from the servers.
  fields:
    vin:
      name: VIN
      description: your vehicle
      required: true
      selector:
        device:
          integration: audiconnect
    action:
      name: Action
      description: > The action to be executed. Possible choices, depending on subscription options, include 'lock', 
      'unlock', 'start_climatisation', 'stop_climatisation, 'start_charger', 'start_timed_charger', 'stop_charger', 
      'start_preheater', 'stop_preheater, 'start_window_heating', 'stop_window_heating'
      example: lock
