---
name: Check Lint

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check the code
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
